/**
 * lib/parser.ts — Markdown response parser for DevChange AI
 *
 * Parses the raw LLM markdown response into the structured
 * AnalysisResult type.
 */

import type { AnalysisResult } from "@/types";

/**
 * Normalize a heading so small formatting differences from the LLM
 * do not break parsing.
 */
function normalizeHeading(heading: string): string {
  return heading
    .trim()
    .toLowerCase()
    .replace(/\s*\/\s*/g, "/")
    .replace(/\s*&\s*/g, " and ")
    .replace(/\s+/g, " ")
    .replace(/[.:]+$/g, "")
    .trim();
}

/**
 * Map normalized heading names to AnalysisResult fields.
 */
const HEADING_TO_KEY: Record<string, keyof AnalysisResult> = {
  "change summary": "changeSummary",
  "affected modules": "affectedModules",
  "database impact": "databaseImpact",
  "backend/api impact": "backendApiImpact",
  "frontend/ui impact": "frontendUiImpact",
  "development tasks": "developmentTasks",
  "test cases and risks": "testCasesAndRisks",
};

/**
 * Empty analysis result.
 */
function emptyResult(): AnalysisResult {
  return {
    changeSummary: "",
    affectedModules: "",
    databaseImpact: "",
    backendApiImpact: "",
    frontendUiImpact: "",
    developmentTasks: "",
    testCasesAndRisks: "",
  };
}

/**
 * Parse markdown generated by the LLM.
 *
 * Supports:
 * ## Heading
 * ### Heading
 *
 * and small formatting variations in headings.
 */
export function parseAnalysis(markdown: string): AnalysisResult {
  const result = emptyResult();

  if (!markdown || !markdown.trim()) {
    return result;
  }

  const lines = markdown.replace(/\r\n/g, "\n").split("\n");

  let currentKey: keyof AnalysisResult | null = null;
  let currentContent: string[] = [];
  let parsedAny = false;

  const saveCurrentSection = () => {
    if (!currentKey) return;

    const content = currentContent.join("\n").trim();

    if (content) {
      result[currentKey] = content;
    }

    currentContent = [];
  };

  for (const line of lines) {
    /**
     * Match markdown headings such as:
     * ## Development Tasks
     * ### Development Tasks
     */
    const headingMatch = line.match(/^#{2,3}\s+(.+?)\s*$/);

    if (headingMatch) {
      const heading = normalizeHeading(headingMatch[1]);

      const key = HEADING_TO_KEY[heading];

      if (key) {
        saveCurrentSection();

        currentKey = key;
        currentContent = [];
        parsedAny = true;

        continue;
      }
    }

    /**
     * Ignore content before the first recognized section.
     */
    if (!currentKey) {
      continue;
    }

    currentContent.push(line);
  }

  /**
   * Save the final section.
   */
  saveCurrentSection();

  /**
   * If no recognized headings were found, preserve the complete
   * response instead of losing the AI output.
   */
  if (!parsedAny) {
    result.changeSummary = markdown.trim();
  }

  return result;
}